### PR TITLE
Added https support as well as support for insecure connections

### PR DESCRIPTION
**Pull request by anthcourtney**
When using this plugin, for one environment (at least), I need to make a https connection as well as bypass the ssl certificate check (because the requested domain name does not match my wildcard certificate).

### CODE REVIEW

**Comment by tas50** [comment]
Can you add usage examples in the comment header that show / explain both of the new flags

**Comment by anthcourtney** [comment]
Where is the 'comment header' that you're referring to?

**Comment by tas50** [comment]
See the usage section in this check for a nice example:

https://github.com/sensu-plugins/sensu-plugins-aws/blob/master/bin/check-autoscaling-cpucredits.rb

**Comment by anthcourtney** [comment]
This has been done.

**Pull request merged**
