### PR TITLE
Adjustments for more than one php-fpm pool[nt]

### PR DESCRIPTION
**Pull request by scones**
## Pull Request Checklist

**Is this in reference to an existing issue?**
#### General
- [ ] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)
- [ ] Update README with any necessary configuration snippets
- [ ] Binstubs are created if needed
- [ ] RuboCop passes
- [ ] Existing tests pass 
#### New Plugins
- [ ] Tests
- [ ] Add the plugin to the README
- [ ] Does it have a complete header as outlined [here](http://sensu-plugins.io/docs/developer_guidelines.html#coding-style)
#### Known Compatablity Issues

nt

### CODE REVIEW

**Comment by scones** [comment]
As there are no such things as
- Changelog
- Readme
- Documentation
- Binstubs
- Tests
- Rubocops

Or any of the other mentioned niceties, i will skip all of those checkboxes above.

I just want more than one graph for different php-fpm pools.

**Comment by majormoses** [comment]
@scones can you fix this up?

**Comment by majormoses** [comment]
@scones ya that did not exist at the time (this has been open a long time). Can you rebase and fix this up?

**Comment by majormoses** [comment]
Also I am not sure I like this approach the scheme is already exposed for this reason it feels like this is a useless option IMHO as you could accomplish this by just updating the scheme to your prefered style as was intended when this was written.

**Comment by majormoses** [comment]
closing due to inactivity

**Pull request closed without merging**
